name: Build and Push Docker Image

on:
  push:
    branches:
      - dev
    paths:
      - '.github/workflows/**'
      - 'Dockerfile'
      - 'go.mod'
      - 'go.sum'
      - 'main.go'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set truncated SHA
        run: echo "COMMIT_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Set env-specific variables
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "ROLE=arn:aws:iam::211125342127:role/elastic-prod-github" >> $GITHUB_ENV
            echo "ECR_REPO=public.ecr.aws/elasticscale/elastic-prod-envsidecar" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF}" == "refs/heads/dev" ]]; then
            echo "ROLE=arn:aws:iam::533267114484:role/elastic-staging-github" >> $GITHUB_ENV
            echo "ECR_REPO=public.ecr.aws/j0p9p4q2/elastic-staging-envsidecar" >> $GITHUB_ENV
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.ROLE }}
          aws-region: eu-west-1

      - name: Log in to Amazon ECR public
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ env.ECR_REPO }}:latest
            ${{ env.ECR_REPO }}:${{ env.COMMIT_SHA_SHORT }}

      - name: Logout from Amazon ECR public
        run: docker logout public.ecr.aws