name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - dev
    paths:
      - '.github/workflows/**'
      - 'Dockerfile'
      - 'go.mod'
      - 'go.sum'
      - 'main.go'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set truncated SHA
        id: vars
        run: echo "COMMIT_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Configure AWS credentials for production
        if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::211125342127:role/elastic-prod-github
          aws-region: eu-west-1

      - name: Log in to Amazon ECR public (production)
        if: github.ref == 'refs/heads/main'
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

      - name: Generate semantic version (production)
        if: github.ref == 'refs/heads/main'
        id: semverprod
        uses: paulhatch/semantic-version@v5
        with:
          tag_prefix: ""
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          patch_pattern: "fix:"
          fallback_patch: true

      - name: Build and push Docker image to production
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            public.ecr.aws/elasticscale/elastic-prod-envsidecar:latest
            public.ecr.aws/elasticscale/elastic-prod-envsidecar:${{ env.COMMIT_SHA_SHORT }}
            public.ecr.aws/elasticscale/elastic-prod-envsidecar:${{ steps.semverprod.outputs.version }}

      - name: Logout from Amazon ECR public (production)
        if: github.ref == 'refs/heads/main'
        run: docker logout public.ecr.aws

      - name: Configure AWS credentials for staging
        if: github.ref == 'refs/heads/dev'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::533267114484:role/elastic-staging-github
          aws-region: eu-west-1

      - name: Log in to Amazon ECR public (staging)
        if: github.ref == 'refs/heads/dev'
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

      - name: Generate semantic version (staging)
        if: github.ref == 'refs/heads/dev'
        id: semverstg
        uses: paulhatch/semantic-version@v5
        with:
          tag_prefix: ""
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          patch_pattern: "fix:"
          fallback_patch: true

      - name: Build and push Docker image to staging
        if: github.ref == 'refs/heads/dev'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            public.ecr.aws/j0p9p4q2/elastic-staging-envsidecar:latest
            public.ecr.aws/j0p9p4q2/elastic-staging-envsidecar:${{ env.COMMIT_SHA_SHORT }}
            public.ecr.aws/j0p9p4q2/elastic-staging-envsidecar:${{ steps.semverstg.outputs.version }}

      - name: Logout from Amazon ECR public (staging)
        if: github.ref == 'refs/heads/dev'
        run: docker logout public.ecr.aws