name: Run Unit Tests

on:
  pull_request:
    types: [opened, reopened, synchronize]
  schedule:
    - cron: '0 3 * * *' # every day at 3:00 AM UTC
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'  # Match go.mod
          cache: true         # Enable built-in caching

      - name: Run unit tests
        run: go test -v ./...